### PR TITLE
Updated agent so connection timeouts cause a new DNS resolution, fixing issues where DNS changes.

### PR DESCRIPTION
**Pull request by jason-o-matic**

### CODE REVIEW

**Comment by netshade** [comment]
Looks good, tested locally across 1.8, 1.9, 2.0, 2.1, 2.2 and JRuby, and all seemed mostly good.

I am getting a consistent failing test in JRuby 1.9 that _seems_ unrelated ( it passes in master ):

```
-> % be rspec spec 
  1) Secure without cert verify behaves like Instrumental Agent Instrumental::Agent enabled should allow outgoing metrics to be stopped
     Failure/Error: server.commands.join("\n").should include("increment foo.baz 1 #{tm.to_i}")
       expected "" to include "increment foo.baz 1 1443208811"
```

Do you see same? 
```
-> % ruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]
```

**Comment by jason-o-matic** [comment]
I see the same failure in master:
```
jason@charlie [master] instrumental_agent $ rspec spec/agent_spec.rb:305
Run options: include {:locations=>{"./spec/agent_spec.rb"=>[305]}}              
  1) Secure without cert verify behaves like Instrumental Agent Instrumental::Agent enabled should allow outgoing metrics to be stopped
     Failure/Error: server.commands.join("\n").should include("increment foo.baz 1 #{tm.to_i}")
       expected "" to include "increment foo.baz 1 1443220516"
     Shared Example Group: "Instrumental Agent" called from ./spec/agent_spec.rb:568
     # ./spec/agent_spec.rb:305:in `(root)'

 2/2 |========================= 100 ==========================>| Time: 00:00:01 

Finished in 1.58 seconds
2 examples, 1 failure

Failed examples:

rspec ./spec/agent_spec.rb:298 # Secure without cert verify behaves like Instrumental Agent Instrumental::Agent enabled should allow outgoing metrics to be stopped
jason@charlie [master] instrumental_agent $ ruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]
```
I'll dig a little and see what I can find.

Are we assuming that the travis 1.9.3 failure was bogus since it passed locally?

**Comment by netshade** [comment]
Yeah, I think the Travis failure is bogus since I can get that to pass reliably locally. I wasn't able to get JRuby to pass in either branch locally, but I'll try again and see what happens.

**Comment by netshade** [comment]
After some more looking at this, I think the test is bad, and the badness of the test is exhibited more clearly in JRuby ( which would allow for parallel operation, and thus exhibit the bad conditions ). In any case, not related to this PR, so :+1:.

**Pull request merged**
